### PR TITLE
fix(circle-pie): Fixed several display bugs in circle pie component

### PR DESCRIPTION
**Pull request by shinuza**
- Fixed default value
- Capped max value to 100 percent to avoid bugs
- Fixed and issue were filling the circle pie completely made it disappear
- Fixed centering

### CODE REVIEW

**Comment by shinuza** [comment]
Before:
screen shot 2017-03-10 at 09 48 47


After
screen shot 2017-03-10 at 09 56 40

**Comment by jennifer-shehane** [comment]
Would like to see this merged in. This project doesn't have a .travis.yml file, so these tests setup to run on PR are not setup correctly. 

I've forked the project and merged in this PR and other fixes and also have it running in CI. I ideally would rather work in this project, and please feel free to pull from my fork if I'm mistaken, but it this repo was looking dead since there have been no commits in 7 months. 

https://github.com/cypress-io/salad-ui

**Comment by samueldelesque** [comment]
Hey @jennifer-shehane. Yeah I switched the NPM repo to point to https://github.com/samueldelesque/salad-ui since I no longer work at Dailymotion and can't commit to this repo. Would be happy to update the NPM to point to Cypress's fork if you are interested in maintaining this?

**Comment by samueldelesque** [comment]
I would like to update it to React 16 as well :)

**Comment by samueldelesque** [comment]
Merged in https://github.com/samueldelesque/salad-ui

**Pull request closed without merging**
